# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('userpassword', models.CharField(max_length=40)),
                ('useremail', models.CharField(max_length=30)),
                ('userphone', models.CharField(max_length=11)),
            ],
        ),
    ]
