# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userpic',
            field=models.ImageField(default='/static/images/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='useremail',
            field=models.CharField(default='', max_length=30),
        ),
    ]
