# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artical',
            old_name='gclick',
            new_name='click',
        ),
    ]
