# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_articles', '0003_auto_20171220_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
